# Generated by Django 4.2.15 on 2024-08-28 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rfqs', '0001_initial'),
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfq',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_rfq', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rfq',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='rfq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='rfqs.rfq'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='rfq',
            index=models.Index(fields=['product', 'buyer', 'rfq_date'], name='rfqs_rfq_product_bfc8b5_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['rfq', 'quotation_date'], name='rfqs_quotat_rfq_id_9e87b9_idx'),
        ),
    ]
