# Generated by Django 4.2.15 on 2024-08-15 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='price_at_purchase',
        ),
    ]
