# Generated by Django 4.2.15 on 2024-08-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='rfq',
            name='api_rfq_product_375bbf_idx',
        ),
        migrations.RenameField(
            model_name='rfq',
            old_name='buyer_id',
            new_name='buyer',
        ),
        migrations.AddIndex(
            model_name='rfq',
            index=models.Index(fields=['product', 'buyer', 'rfq_date'], name='api_rfq_product_07f64b_idx'),
        ),
    ]
