# Generated by Django 4.2.15 on 2024-08-20 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_rfq_api_rfq_product_375bbf_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='quotation',
            name='api_quotati_rfq_id_110686_idx',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='seller',
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['rfq', 'quotation_date'], name='api_quotati_rfq_id_36cbd4_idx'),
        ),
    ]
