# Generated by Django 4.2.15 on 2024-08-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_quotation_api_quotati_rfq_id_110686_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfq',
            name='rfq_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
