# Generated by Django 4.2.15 on 2024-09-18 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ('-start_time',)},
        ),
    ]
