# Generated by Django 4.2.15 on 2024-10-14 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_rating_product_reviews_count_and_more'),
        ('user_auth', '0002_customuser_bio_customuser_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='viewed_products',
            field=models.ManyToManyField(blank=True, related_name='viewed_by', to='products.product'),
        ),
    ]
