
MEASUREMENT_CHOICES = [
    ('pieces', 'pieces'),
    ('kg', 'kilograms'),
    ('liters', 'liters'),
    ('meters', 'meters'),
    ('boxes', 'boxes'),
    ('acres', 'acres'),
    ('amperes', 'amperes'),
    ('bags', 'bags'),
    ('barrels', 'barrels'),
    ('blades', 'blades'),
    ('bushels', 'bushels'),
    ('carats', 'carats'),
    ('cartons', 'cartons'),
    ('cases', 'cases'),
    ('centimeters', 'centimeters'),
    ('chains', 'chains'),
    ('combos', 'combos'),
    ('cubic centimeters', 'cubic centimeters'),
    ('cubic feet', 'cubic feet'),
    ('cubic inches', 'cubic inches'),
    ('cubic meters', 'cubic meters'),
    ('cubic yards', 'cubic yards'),
    ('celsius', 'Celsius'),
    ('fahrenheit', 'Fahrenheit'),
    ('dozens', 'dozens'),
    ('drams', 'drams'),
    ('fluid ounces', 'fluid ounces'),
    ('feet', 'feet'),
    ('forty-foot container', 'forty-foot container'),
    ('furlongs', 'furlongs'),
    ('gallons', 'gallons'),
    ('gills', 'gills'),
    ('grains', 'grains'),
    ('grams', 'grams'),
    ('gross', 'gross'),
    ('hectares', 'hectares'),
    ('hertz', 'hertz'),
    ('inches', 'inches'),
    ('kiloamperes', 'kiloamperes'),
    ('kilohertz', 'kilohertz'),
    ('kiloohms', 'kiloohms'),
    ('kilovolts', 'kilovolts'),
    ('kilowatts', 'kilowatts'),
    ('liters', 'liters'),
    ('long tons', 'long tons'),
    ('megahertz', 'megahertz'),
    ('metric tons', 'metric tons'),
    ('miles', 'miles'),
    ('milliamperes', 'milliamperes'),
    ('milligrams', 'milligrams'),
    ('millihertz', 'millihertz'),
    ('milliliters', 'milliliters'),
    ('millimeters', 'millimeters'),
    ('milliohms', 'milliohms'),
    ('millivolts', 'millivolts'),
    ('milliwatts', 'milliwatts'),
    ('nauctical miles', 'nautical miles'),
    ('ohms', 'ohms'),
    ('ounces', 'ounces'),
    ('packs', 'packs'),
    ('pairs', 'pairs'),
    ('pallets', 'pallets'),
    ('parcels', 'parcels'),
    ('perches', 'perches'),
    ('pieces', 'pieces'),
    ('pints', 'pints'),
    ('plants', 'plants'),
    ('poles', 'poles'),
    ('pounds', 'pounds'),
    ('quarts', 'quarts'),
    ('quarters', 'quarters'),
    ('rods', 'rods'),
    ('rolls', 'rolls'),
    ('sets', 'sets'),
    ('sheets', 'sheets'),
    ('short tons', 'short tons'),
    ('square centimeters', 'square centimeters'),
    ('square feet', 'square feet'),
    ('square inches', 'square inches'),
    ('square meters', 'square meters'),
    ('square miles', 'square miles'),
    ('square yards', 'square yards'),
    ('stones', 'stones'),
    ('strands', 'strands'),
    ('tons', 'tons'),
    ('tonnes', 'tonnes'),
    ('trays', 'trays'),
    ('twenty-foot container', 'twenty-foot container'),
    ('units', 'units'),
    ('volts', 'volts'),
    ('watts', 'watts'),
    ('Wp', 'Wp'),
    ('yards', 'yards')
]

STATUS_CHOICE = [
    ('Pending', 'Pending'),
    ('Approved', 'Approved'),
    ('Rejected', 'Rejected'),
]
