# Generated by Django 4.2.15 on 2024-10-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_tiers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='product',
            name='manufactured_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
