# Generated by Django 4.2.15 on 2024-09-07 06:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(1, 'Quoted'), (2, 'Rejected'), (3, 'Accepted')], db_index=True, default=1)),
                ('quotation_date', models.DateField(auto_now_add=True)),
                ('quoted_price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_time', models.DateField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='quotation_attachments/')),
            ],
        ),
        migrations.CreateModel(
            name='RFQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rfq_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('sourcing_quantity', models.IntegerField()),
                ('quantities_measurements', models.CharField(choices=[('pieces', 'pieces'), ('kg', 'kilograms'), ('liters', 'liters'), ('meters', 'meters'), ('boxes', 'boxes'), ('acres', 'acres'), ('amperes', 'amperes'), ('bags', 'bags'), ('barrels', 'barrels'), ('blades', 'blades'), ('bushels', 'bushels'), ('carats', 'carats'), ('cartons', 'cartons'), ('cases', 'cases'), ('centimeters', 'centimeters'), ('chains', 'chains'), ('combos', 'combos'), ('cubic centimeters', 'cubic centimeters'), ('cubic feet', 'cubic feet'), ('cubic inches', 'cubic inches'), ('cubic meters', 'cubic meters'), ('cubic yards', 'cubic yards'), ('celsius', 'Celsius'), ('fahrenheit', 'Fahrenheit'), ('dozens', 'dozens'), ('drams', 'drams'), ('fluid ounces', 'fluid ounces'), ('feet', 'feet'), ('forty-foot container', 'forty-foot container'), ('furlongs', 'furlongs'), ('gallons', 'gallons'), ('gills', 'gills'), ('grains', 'grains'), ('grams', 'grams'), ('gross', 'gross'), ('hectares', 'hectares'), ('hertz', 'hertz'), ('inches', 'inches'), ('kiloamperes', 'kiloamperes'), ('kilohertz', 'kilohertz'), ('kiloohms', 'kiloohms'), ('kilovolts', 'kilovolts'), ('kilowatts', 'kilowatts'), ('liters', 'liters'), ('long tons', 'long tons'), ('megahertz', 'megahertz'), ('metric tons', 'metric tons'), ('miles', 'miles'), ('milliamperes', 'milliamperes'), ('milligrams', 'milligrams'), ('millihertz', 'millihertz'), ('milliliters', 'milliliters'), ('millimeters', 'millimeters'), ('milliohms', 'milliohms'), ('millivolts', 'millivolts'), ('milliwatts', 'milliwatts'), ('nauctical miles', 'nautical miles'), ('ohms', 'ohms'), ('ounces', 'ounces'), ('packs', 'packs'), ('pairs', 'pairs'), ('pallets', 'pallets'), ('parcels', 'parcels'), ('perches', 'perches'), ('pieces', 'pieces'), ('pints', 'pints'), ('plants', 'plants'), ('poles', 'poles'), ('pounds', 'pounds'), ('quarts', 'quarts'), ('quarters', 'quarters'), ('rods', 'rods'), ('rolls', 'rolls'), ('sets', 'sets'), ('sheets', 'sheets'), ('short tons', 'short tons'), ('square centimeters', 'square centimeters'), ('square feet', 'square feet'), ('square inches', 'square inches'), ('square meters', 'square meters'), ('square miles', 'square miles'), ('square yards', 'square yards'), ('stones', 'stones'), ('strands', 'strands'), ('tons', 'tons'), ('tonnes', 'tonnes'), ('trays', 'trays'), ('twenty-foot container', 'twenty-foot container'), ('units', 'units'), ('volts', 'volts'), ('watts', 'watts'), ('Wp', 'Wp'), ('yards', 'yards')], default='pieces', max_length=255)),
                ('detailed_requirements', models.TextField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('media', models.FileField(blank=True, null=True, upload_to='medial/')),
            ],
        ),
    ]
