# Generated by Django 4.2.15 on 2024-09-12 13:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rfqs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfq',
            name='suppliers_notified',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
