# Generated by Django 4.2.15 on 2024-09-18 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfqs', '0003_rfq_suppliers_notified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rfq',
            options={'ordering': ['-rfq_date']},
        ),
    ]
